### ISSUE TITLE
Problem with importing lodash

### ISSUE THREAD

**Issue by wpmiro** [yunsii/unplugin-svg-sprite#15]
I have a problem importing lodash. You can solve it by replacing this line.
```javascript
import { get, isPlainObject, omitBy, padStart } from "lodash";
```
On this line in the file: `/src/core/ctx.ts`
```javascript
import pkg from 'lodash';
const { get, isPlainObject, omitBy, padStart } = pkg;
```

I use node.js v20.11.1 and pnpm v8.15.5.

```bash
failed to load config from /Users/serhii/_work/vite-boilerplate/vite.config.js
error during build:
file:///Users/serhii/_work/vite-boilerplate/node_modules/.pnpm/unplugin-svg-sprite@1.2.7/node_modules/unplugin-svg-sprite/dist/chunk-K4L3MOHQ.js:114
import { get, isPlainObject, omitBy, padStart } from "lodash";
         ^^^
SyntaxError: Named export 'get' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'lodash';
const { get, isPlainObject, omitBy, padStart } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadConfigFromBundledFile (file:///Users/serhii/_work/vite-boilerplate/node_modules/.pnpm/vite@4.3.9_@types+node@20.11.30/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64506:21)
    at async loadConfigFromFile (file:///Users/serhii/_work/vite-boilerplate/node_modules/.pnpm/vite@4.3.9_@types+node@20.11.30/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64388:28)
    at async resolveConfig (file:///Users/serhii/_work/vite-boilerplate/node_modules/.pnpm/vite@4.3.9_@types+node@20.11.30/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:63993:28)
    at async build (file:///Users/serhii/_work/vite-boilerplate/node_modules/.pnpm/vite@4.3.9_@types+node@20.11.30/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46318:20)
    at async CAC.<anonymous> (file:///Users/serhii/_work/vite-boilerplate/node_modules/.pnpm/vite@4.3.9_@types+node@20.11.30/node_modules/vite/dist/node/cli.js:812:9)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by yunsii** [comment]
I see, it seems that is a bug for esm.

**Comment by wpmiro** [comment]
@yunsii Please update the npm package

**Comment by yunsii** [comment]
Released https://github.com/yunsii/unplugin-svg-sprite/releases/tag/v1.2.8
